## **African Cup of Nations 2023 Analysis**

## **1. Loading the Dataset**

In [3]:
%pip install statsbombpy

Requirement already satisfied: statsbombpy in ./.venv/lib/python3.12/site-packages (1.22.0)
Requirement already satisfied: pandas in ./.venv/lib/python3.12/site-packages (from statsbombpy) (3.0.5)
Requirement already satisfied: requests in ./.venv/lib/python3.12/site-packages (from statsbombpy) (2.34.2)
Requirement already satisfied: requests-cache in ./.venv/lib/python3.12/site-packages (from statsbombpy) (1.3.3)
Requirement already satisfied: inflect in ./.venv/lib/python3.12/site-packages (from statsbombpy) (7.5.0)
Requirement already satisfied: joblib in ./.venv/lib/python3.12/site-packages (from statsbombpy) (1.5.3)
Requirement already satisfied: more_itertools>=8.5.0 in ./.venv/lib/python3.12/site-packages (from inflect->statsbombpy) (11.1.0)
Requirement already satisfied: typeguard>=4.0.1 in ./.venv/lib/python3.12/site-packages (from inflect->statsbombpy) (4.6.0)
Requirement already satisfied: typing_extensions>=4.14.0 in ./.venv/lib/python3.12/site-packages (from typeguard>=4.0.1->inflect->statsbombpy) (4.16.0)
Requirement already satisfied: numpy>=1.26.0 in ./.venv/lib/python3.12/site-packages (from pandas->statsbombpy) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.12/site-packages (from pandas->statsbombpy) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->statsbombpy) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.12/site-packages (from requests->statsbombpy) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.12/site-packages (from requests->statsbombpy) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in ./.venv/lib/python3.12/site-packages (from requests->statsbombpy) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in ./.venv/lib/python3.12/site-packages (from requests->statsbombpy) (2026.7.22)
Requirement already satisfied: attrs>=21.2 in ./.venv/lib/python3.12/site-packages (from requests-cache->statsbombpy) (26.1.0)
Requirement already satisfied: cattrs>=22.2 in ./.venv/lib/python3.12/site-packages (from requests-cache->statsbombpy) (26.1.0)
Requirement already satisfied: platformdirs>=2.5 in ./.venv/lib/python3.12/site-packages (from requests-cache->statsbombpy) (4.11.3)
Requirement already satisfied: url-normalize>=2.0 in ./.venv/lib/python3.12/site-packages (from requests-cache->statsbombpy) (3.0.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
# Import required libraries for AFCON analysis
import os
import pandas as pd
from statsbombpy import sb

# Optional: display nicer tabular output in notebooks
pd.options.display.max_columns = None
pd.options.display.width = 120

In [5]:
# running this code will print out a table of all competitions available in the StatsBomb dataset, including their IDs

from statsbombpy import sb
comps = sb.competitions()
print(comps[['competition_id','season_id','competition_name','season_name','competition_gender']])

/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

    competition_id  season_id        competition_name season_name competition_gender
0                9        281           1. Bundesliga   2023/2024               male
1                9         27           1. Bundesliga   2015/2016               male
2             1267        107  African Cup of Nations        2023               male
3               16          4        Champions League   2018/2019               male
4               16          1        Champions League   2017/2018               male
..             ...        ...                     ...         ...                ...
75              35         75      UEFA Europa League   1988/1989               male
76              53        315       UEFA Women's Euro        2025             female
77              53        106       UEFA Women's Euro        2022             female
78              72        107       Women's World Cup        2023             female
79              72         30       Women's World Cup        2019             female

[80 rows x 5 columns]

In [6]:
# Pull African Cup of Nations (AFCON) 2023 matches and events
# Assumes `comps` and `sb` are already defined (run previous cell first)

# Find AFCON competition/season row
afcon = comps[comps['competition_name'].str.contains('African Cup of Nations', case=False, na=False)]
print(afcon[['competition_id','season_id','competition_name','season_name']])
if afcon.empty:
    raise ValueError('African Cup of Nations not found in competitions list')

comp_id = int(afcon.iloc[0]['competition_id'])
season_id = int(afcon.iloc[0]['season_id'])

# Download matches for the competition/season
matches = sb.matches(competition_id=comp_id, season_id=season_id)
print(f'Found {len(matches)} matches for competition_id={comp_id}, season_id={season_id}')
matches.to_csv('afcon_matches_2023.csv', index=False)

# Create folder and download events for each match (may take time)
import os
os.makedirs('afcon_events', exist_ok=True)

for mid in matches['match_id']:
    try:
        events = sb.events(match_id=int(mid))
        # some sb.events returns a DataFrame-like object; try to save as CSV
        events.to_csv(os.path.join('afcon_events', f'events_{mid}.csv'), index=False)
    except Exception as e:
        print(f'Failed to fetch events for match {mid}: {e}')

   competition_id  season_id        competition_name season_name
2            1267        107  African Cup of Nations        2023

/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Found 52 matches for competition_id=1267, season_id=107

/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/workspaces/Football_Data_Analysis_HQ/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [7]:
# Clean AFCON preview: shape, columns, dtypes, and first few rows only
print('AFCON matches shape:', matches.shape)
print('Columns:', list(matches.columns))
print('\nDtypes:')
print(matches.dtypes)
print('\nFirst few rows:')
matches.head()

AFCON matches shape: (52, 55)
Columns: ['match_id', 'match_date', 'kick_off', 'home_score', 'away_score', 'match_status', 'match_status_360', 'last_updated', 'last_updated_360', 'match_week', 'competition_id', 'competition_country_name', 'competition_name', 'competition', 'season_id', 'season', 'home_team_id', 'home_team', 'home_team_gender', 'home_team_group', 'home_team_country_id', 'home_team_country_name', 'away_team_id', 'away_team', 'away_team_gender', 'away_team_group', 'away_team_country_id', 'away_team_country_name', 'competition_stage_id', 'competition_stage', 'stadium_id', 'stadium', 'stadium_country_id', 'stadium_country_name', 'referee_id', 'referee', 'referee_country_id', 'referee_country_name', 'home_managers', 'away_managers', 'home_manager_id', 'home_manager_name', 'home_manager_nickname', 'home_manager_dob', 'home_manager_country_id', 'home_manager_country_name', 'away_manager_id', 'away_manager_name', 'away_manager_nickname', 'away_manager_dob', 'away_manager_country_id', 'away_manager_country_name', 'data_version', 'shot_fidelity_version', 'xy_fidelity_version']

Dtypes:
match_id                      int64
match_date                      str
kick_off                        str
home_score                    int64
away_score                    int64
match_status                    str
match_status_360                str
last_updated                    str
last_updated_360                str
match_week                    int64
competition_id                int64
competition_country_name        str
competition_name                str
competition                     str
season_id                     int64
season                          str
home_team_id                  int64
home_team                       str
home_team_gender                str
home_team_group              object
home_team_country_id          int64
home_team_country_name          str
away_team_id                  int64
away_team                       str
away_team_gender                str
away_team_group              object
away_team_country_id          int64
away_team_country_name          str
competition_stage_id          int64
competition_stage               str
stadium_id                    int64
stadium                         str
stadium_country_id            int64
stadium_country_name            str
referee_id                    int64
referee                         str
referee_country_id            int64
referee_country_name            str
home_managers                   str
away_managers                   str
home_manager_id               int64
home_manager_name               str
home_manager_nickname           str
home_manager_dob                str
home_manager_country_id       int64
home_manager_country_name       str
away_manager_id               int64
away_manager_name               str
away_manager_nickname           str
away_manager_dob                str
away_manager_country_id       int64
away_manager_country_name       str
data_version                    str
shot_fidelity_version           str
xy_fidelity_version             str
dtype: object

First few rows:

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,competition_id,competition_country_name,competition_name,competition,season_id,season,home_team_id,home_team,home_team_gender,home_team_group,home_team_country_id,home_team_country_name,away_team_id,away_team,away_team_gender,away_team_group,away_team_country_id,away_team_country_name,competition_stage_id,competition_stage,stadium_id,stadium,stadium_country_id,stadium_country_name,referee_id,referee,referee_country_id,referee_country_name,home_managers,away_managers,home_manager_id,home_manager_name,home_manager_nickname,home_manager_dob,home_manager_country_id,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,data_version,shot_fidelity_version,xy_fidelity_version
0,3922240,2024-01-28,20:00:00.000,1,1,available,unscheduled,2026-05-02T14:23:45.490823,NaN,4,1267,Africa,African Cup of Nations,Africa - African Cup of Nations,107,2023,774,Egypt,male,None,66,Egypt,4881,Congo DR,male,None,52,"Congo, (Kinshasa)",33,Round of 16,1001497,Stade Laurent Pokou,55,Côte d'Ivoire,2323,Abongile Tom,211,South Africa,Rui Carlos Pinho da Vitória,Sébastien Desabre,261,Rui Carlos Pinho da Vitória,Rui Vitória,1970-04-16,183,Portugal,5011,Sébastien Desabre,NaN,1976-08-02,78,France,1.1.0,2,2
1,3920399,2024-01-19,14:00:00.000,3,0,available,unscheduled,2026-05-02T05:59:06.800066,NaN,2,1267,Africa,African Cup of Nations,Africa - African Cup of Nations,107,2023,4924,Cape Verde Islands,male,None,41,Cape Verde,4978,Mozambique,male,None,155,Mozambique,10,Group Stage,117916,Stade Félix Houphouët-Boigny,55,Côte d'Ivoire,1003709,Samir Guezzaz,154,Morocco,Pedro Leitão Brito,Francisco Queriol Conde Júnior,1000417,Pedro Leitão Brito,Bubista,1970-01-06,41,Cape Verde,1001646,Francisco Queriol Conde Júnior,Chiquinho Conde,1965-11-22,155,Mozambique,1.1.0,2,2
2,3920413,2024-01-23,17:00:00.000,2,3,available,unscheduled,2026-05-02T05:58:38.856282,NaN,3,1267,Africa,African Cup of Nations,Africa - African Cup of Nations,107,2023,4934,Gambia,male,None,83,Gambia,2722,Cameroon,male,None,39,Cameroon,10,Group Stage,1001316,Stade de Bouaké,55,Côte d'Ivoire,1000963,Bamlak Tessema Weyesa,72,Ethiopia,Tom Saintfiet,Rigobert Song Bahanag,1000972,Tom Saintfiet,NaN,1973-03-29,22,Belgium,1001250,Rigobert Song Bahanag,NaN,1976-07-01,39,Cameroon,1.1.0,2,2
3,3920400,2024-01-19,17:00:00.000,3,1,available,unscheduled,2026-05-02T05:58:12.096660,NaN,2,1267,Africa,African Cup of Nations,Africa - African Cup of Nations,107,2023,787,Senegal,male,None,202,Senegal,2722,Cameroon,male,None,39,Cameroon,10,Group Stage,1000822,Stade Charles Konan Banny de Yamoussoukro,55,Côte d'Ivoire,1003531,Mahmood Ali Mahmood Ismail,216,Sudan,Aliou Cissé,Rigobert Song Bahanag,635,Aliou Cissé,NaN,1976-03-24,202,Senegal,1001250,Rigobert Song Bahanag,NaN,1976-07-01,39,Cameroon,1.1.0,2,2
4,3920409,2024-01-22,17:00:00.000,0,1,available,unscheduled,2026-05-02T05:57:00.296561,NaN,3,1267,Africa,African Cup of Nations,Africa - African Cup of Nations,107,2023,4894,Guinea-Bissau,male,None,96,Guinea-Bissau,775,Nigeria,male,None,166,Nigeria,10,Group Stage,117916,Stade Félix Houphouët-Boigny,55,Côte d'Ivoire,1005493,Bouchra Karboubi,154,Morocco,Baciro Candé,José Vítor dos Santos Peseiro,1000429,Baciro Candé,NaN,1967-04-06,96,Guinea-Bissau,523,José Vítor dos Santos Peseiro,José Peseiro,1960-04-04,183,Portugal,1.1.0,2,2

In [8]:
# Check for missing values in each column
print('Missing values per column:')
missing_counts = matches.isnull().sum()
print(missing_counts[missing_counts > 0] if missing_counts.sum() > 0 else "No missing values found!")
print(f'\nTotal missing values: {matches.isnull().sum().sum()}')

Missing values per column:
last_updated_360         51
home_team_group          52
away_team_group          52
home_manager_nickname    33
home_manager_dob          2
away_manager_nickname    42
away_manager_dob          1
dtype: int64

Total missing values: 233

In [9]:
# Check for duplicate rows
print('Duplicate rows:', matches.duplicated().sum())

if matches.duplicated().sum() > 0:
    print('\nDuplicate records:')
    display(matches[matches.duplicated(keep=False)].sort_values(by=list(matches.columns)))
else:
    print('No duplicate rows found!')

Duplicate rows: 0
No duplicate rows found!

In [10]:
# Validate key fields before cleaning
parsed_dates = pd.to_datetime(matches['match_date'], errors='coerce')

print('Unique match IDs:', matches['match_id'].is_unique)
print('Invalid match dates:', parsed_dates.isna().sum())
print('Negative scores:', ((matches['home_score'] < 0) | (matches['away_score'] < 0)).sum())
print('Competition IDs:', matches['competition_id'].unique())
print('Season IDs:', matches['season_id'].unique())
print('Match date range:', parsed_dates.min().date(), 'to', parsed_dates.max().date())
print('Number of matches:', len(matches))

Unique match IDs: True
Invalid match dates: 0
Negative scores: 0
Competition IDs: [1267]
Season IDs: [107]
Match date range: 2024-01-13 to 2024-02-11
Number of matches: 52

## **2. Data Cleaning and Manipulation**

In [11]:
# Create a working copy so the original dataset remains unchanged
matches_clean = matches.copy()

print('Working copy created:', matches_clean.shape)

Working copy created: (52, 55)

In [ ]:
# Convert dates, times, scores, and identifiers to analysis-friendly types
matches_clean['match_date'] = pd.to_datetime(matches_clean['match_date'], errors='coerce')
matches_clean['kick_off'] = pd.to_timedelta(matches_clean['kick_off'], errors='coerce')

numeric_columns = [
    'match_id', 'home_score', 'away_score', 'match_week',
    'competition_id', 'season_id', 'home_team_id', 'away_team_id'
]
for column in numeric_columns:
    matches_clean[column] = pd.to_numeric(matches_clean[column], errors='coerce').astype('Int64')

# Remove accidental whitespace from text fields while preserving missing values
text_columns = matches_clean.columns[matches_clean.dtypes == 'object']
for column in text_columns:
    matches_clean[column] = matches_clean[column].str.strip()

print('Date dtype:', matches_clean['match_date'].dtype)
print('Kick-off dtype:', matches_clean['kick_off'].dtype)
print('Invalid dates:', matches_clean['match_date'].isna().sum())
print('Invalid kick-off values:', matches_clean['kick_off'].isna().sum())

Date dtype: datetime64[us]
Kick-off dtype: timedelta64[us]
Invalid dates: 0
Invalid kick-off values: 0

/tmp/ipykernel_2837/697407765.py:13: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = matches_clean.select_dtypes(include='object').columns

In [13]:
# Add match-level outcome and goal statistics
matches_clean['result'] = 'Draw'
matches_clean.loc[
    matches_clean['home_score'] > matches_clean['away_score'], 'result'
] = 'Home Win'
matches_clean.loc[
    matches_clean['home_score'] < matches_clean['away_score'], 'result'
] = 'Away Win'

matches_clean['total_goals'] = matches_clean['home_score'] + matches_clean['away_score']
matches_clean['goal_difference'] = matches_clean['home_score'] - matches_clean['away_score']
matches_clean['both_teams_scored'] = (
    (matches_clean['home_score'] > 0) & (matches_clean['away_score'] > 0)
)

print(matches_clean[['home_team', 'away_team', 'home_score', 'away_score', 'result', 'total_goals']].head())

            home_team   away_team  home_score  away_score    result  total_goals
0               Egypt    Congo DR           1           1      Draw            2
1  Cape Verde Islands  Mozambique           3           0  Home Win            3
2              Gambia    Cameroon           2           3  Away Win            5
3             Senegal    Cameroon           3           1  Home Win            4
4       Guinea-Bissau     Nigeria           0           1  Away Win            1

In [14]:
# Validate the cleaned dataset before analysis
validation_checks = {
    'Rows preserved': len(matches_clean) == len(matches),
    'Match IDs remain unique': matches_clean['match_id'].is_unique,
    'No invalid dates': matches_clean['match_date'].notna().all(),
    'No invalid scores': (
        matches_clean[['home_score', 'away_score']].notna().all().all()
        and (matches_clean[['home_score', 'away_score']] >= 0).all().all()
    ),
    'No team plays itself': (matches_clean['home_team'] != matches_clean['away_team']).all(),
    'Every match has a result': matches_clean['result'].notna().all()
}

for check, passed in validation_checks.items():
    print(f'{check}: {"PASS" if passed else "FAIL"}')

matches_clean.head()

Rows preserved: PASS
Match IDs remain unique: PASS
No invalid dates: PASS
No invalid scores: PASS
No team plays itself: PASS
Every match has a result: PASS

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,competition_id,competition_country_name,competition_name,competition,season_id,season,home_team_id,home_team,home_team_gender,home_team_group,home_team_country_id,home_team_country_name,away_team_id,away_team,away_team_gender,away_team_group,away_team_country_id,away_team_country_name,competition_stage_id,competition_stage,stadium_id,stadium,stadium_country_id,stadium_country_name,referee_id,referee,referee_country_id,referee_country_name,home_managers,away_managers,home_manager_id,home_manager_name,home_manager_nickname,home_manager_dob,home_manager_country_id,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,data_version,shot_fidelity_version,xy_fidelity_version,result,total_goals,goal_difference,both_teams_scored
0,3922240,2024-01-28,0 days 20:00:00,1,1,available,unscheduled,2026-05-02T14:23:45.490823,NaN,4,1267,Africa,African Cup of Nations,Africa - African Cup of Nations,107,2023,774,Egypt,male,None,66,Egypt,4881,Congo DR,male,None,52,"Congo, (Kinshasa)",33,Round of 16,1001497,Stade Laurent Pokou,55,Côte d'Ivoire,2323,Abongile Tom,211,South Africa,Rui Carlos Pinho da Vitória,Sébastien Desabre,261,Rui Carlos Pinho da Vitória,Rui Vitória,1970-04-16,183,Portugal,5011,Sébastien Desabre,NaN,1976-08-02,78,France,1.1.0,2,2,Draw,2,0,True
1,3920399,2024-01-19,0 days 14:00:00,3,0,available,unscheduled,2026-05-02T05:59:06.800066,NaN,2,1267,Africa,African Cup of Nations,Africa - African Cup of Nations,107,2023,4924,Cape Verde Islands,male,None,41,Cape Verde,4978,Mozambique,male,None,155,Mozambique,10,Group Stage,117916,Stade Félix Houphouët-Boigny,55,Côte d'Ivoire,1003709,Samir Guezzaz,154,Morocco,Pedro Leitão Brito,Francisco Queriol Conde Júnior,1000417,Pedro Leitão Brito,Bubista,1970-01-06,41,Cape Verde,1001646,Francisco Queriol Conde Júnior,Chiquinho Conde,1965-11-22,155,Mozambique,1.1.0,2,2,Home Win,3,3,False
2,3920413,2024-01-23,0 days 17:00:00,2,3,available,unscheduled,2026-05-02T05:58:38.856282,NaN,3,1267,Africa,African Cup of Nations,Africa - African Cup of Nations,107,2023,4934,Gambia,male,None,83,Gambia,2722,Cameroon,male,None,39,Cameroon,10,Group Stage,1001316,Stade de Bouaké,55,Côte d'Ivoire,1000963,Bamlak Tessema Weyesa,72,Ethiopia,Tom Saintfiet,Rigobert Song Bahanag,1000972,Tom Saintfiet,NaN,1973-03-29,22,Belgium,1001250,Rigobert Song Bahanag,NaN,1976-07-01,39,Cameroon,1.1.0,2,2,Away Win,5,-1,True
3,3920400,2024-01-19,0 days 17:00:00,3,1,available,unscheduled,2026-05-02T05:58:12.096660,NaN,2,1267,Africa,African Cup of Nations,Africa - African Cup of Nations,107,2023,787,Senegal,male,None,202,Senegal,2722,Cameroon,male,None,39,Cameroon,10,Group Stage,1000822,Stade Charles Konan Banny de Yamoussoukro,55,Côte d'Ivoire,1003531,Mahmood Ali Mahmood Ismail,216,Sudan,Aliou Cissé,Rigobert Song Bahanag,635,Aliou Cissé,NaN,1976-03-24,202,Senegal,1001250,Rigobert Song Bahanag,NaN,1976-07-01,39,Cameroon,1.1.0,2,2,Home Win,4,2,True
4,3920409,2024-01-22,0 days 17:00:00,0,1,available,unscheduled,2026-05-02T05:57:00.296561,NaN,3,1267,Africa,African Cup of Nations,Africa - African Cup of Nations,107,2023,4894,Guinea-Bissau,male,None,96,Guinea-Bissau,775,Nigeria,male,None,166,Nigeria,10,Group Stage,117916,Stade Félix Houphouët-Boigny,55,Côte d'Ivoire,1005493,Bouchra Karboubi,154,Morocco,Baciro Candé,José Vítor dos Santos Peseiro,1000429,Baciro Candé,NaN,1967-04-06,96,Guinea-Bissau,523,José Vítor dos Santos Peseiro,José Peseiro,1960-04-04,183,Portugal,1.1.0,2,2,Away Win,1,-1,False